

atendimento_cad_dic = {'tipo_atendimento': {'1': 'Cadastro: atualização cadastral CadPSR+',
                                            '2': 'Cadastro: Pessoa CadPSR+',
                                            '3': 'Denúncia: violência sofrida pela própria Pessoa',
                                            '4': 'Denúncia: violência sofrida por terceiros',
                                            '5': 'Doação: agasalhos/cobertores',
                                            '6': 'Doação: cesta básica',
                                            '7': 'Doação: itens de higiene pessoal',
                                            '8': 'Encaminhamento: Centro Pop',
                                            '9': 'Encaminhamento: clínicas de Saúde Pública',
                                            '10': 'Encaminhamento: CRAS',
                                            '11': 'Encaminhamento: CREAS',
                                            '12': 'Encaminhamento: Poupa Tempo - Documentação',
                                            '13': 'Encaminhamento: Secretaria de Educação',
                                            '14': 'Encaminhamento: UBS',
                                            '15': 'Higienização Pessoal',
                                            '16': 'Refeição: Bom Prato',
                                            '17': 'Solicitação: doação de cesta básica',
                                            '18': 'Solicitação: doação de agasalhos/cobertores',
                                           }
                      }


colaborador_cad_dic = {'iniciativa': {'1': 'Publica',
                                      '2': 'Privada',
                                      },
                       'tipo': {'0': 'Desenvolvedor',
                                '1': 'Administrador',
                                '2': 'Gestor',
                                '3': 'Coordenador',
                                '4': 'Gerente',
                                '5': 'Colaborador(a)',
                       },
                      }

documento_cad = {'sistema': 'CadPSR'

}


entidade_cad_dic = {'entidade': {'0': 'Desenvolvedora CadPSR+',
                                 '1': 'Centro POP Santo André',
                                 '2': 'Centro POP São Bernardo do Campo',
                                 '3': 'CRAS Santo André - Centro',
                                 '4': 'CRAS São Bernardo do Campo - Centro',
                                 '5': 'CREAS Santo André',
                                 '6': 'CREAS São Bernardo do Campo',
                                 '7': 'Associação Amores, Lutas & Vidas',
                                 '8': 'Associação Plenos Direitos',
                                 '9': 'Fundação Faça Valer Direitos e Vida',
                                 '10': 'Fundação Pessoas & Diversidades',
                                },
                    'cidade': {'1': 'Santo André',
                               '2': 'São Bernardo do Campo',
                              },
                    'iniciativa': {'1': 'Pública',
                                   '2': 'Privada',
                                  },
                    'tipo': {'0': 'Desenvolvimento',
                             '1': 'Associação',
                             '2': 'Centro POP',
                             '3': 'CRAS',
                             '4': 'CREAS',
                             '5': 'Fundação',
                            },
                    'natureza': {'0': 'Desenvolvedora',
                                 '1': 'Administradora',
                                 '2': 'Gestora',
                                 '3': 'Coordenadora',
                                 '4': 'Acolhedora',
                                },
                   }


pessoa_cad_dic = {'cidade': {'1': 'Sao Bernardo do Campo',
                             },
                  'etnia': {'1': 'Amarela',
                             '2': 'Branca',
                             '3': 'Índigena',
                             '4': 'Parda',
                             '5': 'Preta',
                             '6': 'Não informado',
                             },
                  'identidade_genero': {'1': 'Agênero',
                                         '2': 'Cisgênero',
                                         '3': 'Não Binário',
                                         '4': 'Transgênero',
                                         '5': 'Não informado'
                                         },
                  'orientacao_sexual': {'1': 'Assexual',
                                         '2': 'Bissexual',
                                         '3': 'Heterossexual',
                                         '4': 'Homossexual',
                                         '5': 'Pansexual',
                                         '6': 'Não informado',
                                         },
                  'sexo': {'1': 'Feminino',
                            '2': 'Maculino',
                            '3': 'Não informado',
                            },
                  'uf': {'ac': 'AC', 'al': 'AL', 'am': 'AM', 'ap': 'AP', 'ba': 'BA',
                         'ce': 'CE', 'df': 'DF', 'es': 'ES', 'go': 'GO', 'ma': 'MA',
                         'mg': 'MG', 'ms': 'MS', 'mt': 'MT', 'pa': 'PA', 'pb': 'PB',
                         'pe': 'PE', 'pi': 'PI', 'rj': 'RJ', 'rn': 'RN', 'ro': 'RO',
                         'rr': 'RR', 'rs': 'RS', 'sc': 'SC', 'se': 'SE', 'sp': 'SP',
                         'to': 'TO',}
                  }


questionario_pessoa_estrangeira = {'questao_1': {'1': '1 - Motivos econômicos',
                                                 '2': '2 - Motivos políticos',
                                                 '3': '3 - Motivos de guerra',
                                                 '4': '4 - Não',
                                                }
                                  }


questionario = {'questao_1': {'1': '1 - Rua',
                              '2': '2 - Albergue',
                              '3': '3 - Domicílio particular',
                              '4': '4 - Outro',
                              '5': '5 - Não respondeu',
                              },
                'questao_2': {'1': '1 - Até seis meses',
                              '2': '2 - Entre seis meses e 1 ano',
                              '3': '3 - Entre 1 e 2 anos',
                              '4': '4 - Entre 2 e 5 anos',
                              '5': '5 - Entre 5 e 10 anos',
                              '6': '6 - Mais de 10 anos',
                              '7': '7 - Não respondeu',
                              },
                'questao_3': {'1': '1 - Perda de moradia',
                              '2': '2 - Ameaça/violência',
                              '3': '3 - Problemas com familiares/companheiro(a)',
                              '4': '4 - Alcoolismo/drogas',
                              '5': '5 - Desemprego',
                              '6': '6 - Trabalho',
                              '7': '7 - Tratamento de saúde',
                              '8': '8 - Preferência/opção própria',
                              '9': '9 - Outro',
                              '10': '10 - Não sabe/não se lembra',
                              '11': '11 - Não respondeu',
                              },
                'questao_4': {'1': '1 - Até seis meses',
                              '2': '2 - Entre seis meses e 1 ano',
                              '3': '3 - Entre 1 e 2 anos',
                              '4': '4 - Entre 2 e 5 anos',
                              '5': '5 - Entre 5 e 10 anos',
                              '6': '6 - Mais de 10 anos',
                              '7': '7 - Não respondeu',
                              },
                'questao_5': {'1': '1 - Sim',
                              '2': '2 - Não',
                              '3': '3 - Não respondeu',
                              },
                'questao_6': {'1': '1 - Todo dia',
                              '2': '2 - Toda semana',
                              '3': '3 - Todo mês',
                              '4': '4 - Todo ano',
                              '5': '5 - Quase nunca',
                              '6': '6 - Nunca',
                              '7': '7 - Não respondeu',
                              },
                'questao_7': {'1': '1 - Escola',
                              '2': '2 - Associação',
                              '3': '3 - Cooperativa',
                              '4': '4 - Movimento social',
                              '5': '5 - Não sabe/não se lembra',
                              '6': '6 - Não respondeu',
                              },
                'questao_8': {'1': '1 - Centro de Referência da Assistência Social - CRAS',
                              '2': '2 - Centro de Referência Especializado da Assistência Social - CREAS',
                              '3': '3 - Centro de Referência para População em Situação de Rua - Centro Pop',
                              '4': '4 - Instituição de Acolhimento Governamental (albergue/abrigo/outro)',
                              '5': '5 - Instituição de Acolhimento Não-Governamental (institução beneficente privada/outro)',
                              '6': '6 - Hospital/clínica geral',
                              '7': '7 - Nenhum',
                              '8': '8 - Não respondeu',
                              },
                'questao_9': {'1': '1 - Sim',
                              '2': '2 - Não',
                              '3': '3 - Não sabe',
                              '4': '4 - Não respondeu',
                              },
                'questao_10': {'1': '1 - Construção civil',
                               '2': '2 - Guardador de carro/fileira',
                               '3': '3 - Carregador/estivador',
                               '4': '4 - Catador de material reciclável',
                               '5': '5 - Serviços gerais/limpeza/outros',
                               '6': '6 - Pede dinheiro',
                               '7': '7 - Vendas',
                               '8': '8 - Outro',
                               '9': '9 - Não respondeu',
                               },
                'questao_12': {'1': '1 - Até seis meses',
                               '2': '2 - Entre seis meses e 1 ano',
                               '3': '3 - Entre 1 e 2 anos',
                               '4': '4 - Entre 2 e 5 anos',
                               '5': '5 - Entre 5 e 10 anos',
                               '6': '6 - Mais de 10 anos',
                               '7': '7 - Não respondeu',
                               },
                'questao_13': {'1': '1 - Deficiência auditiva',
                               '2': '2 - Deficiência intelectual',
                               '3': '3 - Deficiência motora',
                               '4': '4 - Deficiência múltipla',
                               '5': '5 - Deficiência psicossocial',
                               '6': '6 - Deficiência visual',
                               '7': '7 - Outra deficiência',
                               '8': '8 - Não possui deficiência',
                               '9': '9 - Não respondeu',
                               },
                'questao_14': {'1': '1 - Sim, primeira dose',
                               '2': '2 - Sim, segunda dose',
                               '3': '3 - Sim, terceira dose (dose de reforço)',
                               '4': '4 - Não',
                               '5': '5 - Não respondeu',
                               }
                }
